#!/usr/bin/env python3
"""Small state helper for the SAM Codex plugin."""

from __future__ import annotations

import argparse
import json
import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path


DOC_ROOT = Path("docs") / "arquitecture"
STATE_PATH = DOC_ROOT / ".sam" / "state.json"

PHASE_DIRS = [
    DOC_ROOT / "01-architectural-requirements",
    DOC_ROOT / "02-architectural-design",
    DOC_ROOT / "03-architectural-documentation",
    DOC_ROOT / "04-architectural-implementation",
]

ARTIFACTS = {
    "project-brief": DOC_ROOT / "project-brief.md",
    "phase-1-input": DOC_ROOT / "01-architectural-requirements" / "input.md",
    "phase-1-drivers": DOC_ROOT / "01-architectural-requirements" / "architecture-drivers.md",
    "phase-2-input": DOC_ROOT / "02-architectural-design" / "input.md",
    "phase-2-iteration-plan": DOC_ROOT / "02-architectural-design" / "iteration-plan.md",
    "phase-2-decisions": DOC_ROOT / "02-architectural-design" / "design-decisions.md",
    "phase-3-input": DOC_ROOT / "03-architectural-documentation" / "input.md",
    "phase-3-document": DOC_ROOT / "03-architectural-documentation" / "architecture-document.md",
    "phase-4-input": DOC_ROOT / "04-architectural-implementation" / "input.md",
    "phase-4-implementation-plan": DOC_ROOT / "04-architectural-implementation" / "implementation-plan.md",
    "phase-4-design-system": DOC_ROOT / "04-architectural-implementation" / "design-system.md",
}

GATES = {
    "brief": ["project-brief"],
    "phase-1-drivers": ["phase-1-drivers"],
    "phase-2-design": ["phase-2-iteration-plan", "phase-2-decisions"],
    "phase-3-document": ["phase-3-document"],
    "phase-4-implementation": ["phase-4-implementation-plan"],
}

NEXT_GATE = {
    "brief": "phase-1-drivers",
    "phase-1-drivers": "phase-2-design",
    "phase-2-design": "phase-3-document",
    "phase-3-document": "phase-4-implementation",
    "phase-4-implementation": "complete",
}


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def fail(message: str, code: int = 2) -> None:
    print(message)
    raise SystemExit(code)


def default_state() -> dict:
    return {"version": 1, "currentGate": "brief", "artifacts": {}, "approvals": []}


def load_state() -> dict:
    if not STATE_PATH.exists():
        return default_state()
    return json.loads(STATE_PATH.read_text(encoding="utf-8"))


def save_state(state: dict) -> None:
    STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    STATE_PATH.write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")


def write_once(path: Path, content: str) -> None:
    if path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def brief_template(name: str) -> str:
    title = name.strip() or "Project"
    return f"""# {title} - Project Brief

## 1. Business Problem

## 2. System Goal

## 3. Initial Scope / MVP

## 4. Stakeholders

## 5. Main Features

## 6. Expected Quality Attributes

## 7. Constraints

## 8. Current Context

## 9. Environments And Operations

## 10. Customer Priorities
"""


def phase_input_template(phase: str) -> str:
    return f"""# {phase} Input

Status: Draft
Generated by: SAM agent
Approved by:
Approved date:
Source artifacts:

## Input

- 
"""


def init(args: argparse.Namespace) -> None:
    DOC_ROOT.mkdir(parents=True, exist_ok=True)
    for directory in PHASE_DIRS:
        directory.mkdir(parents=True, exist_ok=True)

    write_once(ARTIFACTS["project-brief"], brief_template(args.name))
    write_once(ARTIFACTS["phase-1-input"], phase_input_template("Phase 1 - Architectural Requirements"))
    write_once(ARTIFACTS["phase-2-input"], phase_input_template("Phase 2 - Architectural Design"))
    write_once(ARTIFACTS["phase-3-input"], phase_input_template("Phase 3 - Architectural Documentation"))
    write_once(ARTIFACTS["phase-4-input"], phase_input_template("Phase 4 - Architectural Implementation"))

    state = load_state()
    for key in ["project-brief", "phase-1-input", "phase-2-input", "phase-3-input", "phase-4-input"]:
        state["artifacts"].setdefault(key, {"path": str(ARTIFACTS[key]), "status": "draft"})
    save_state(state)
    print(f"Initialized SAM workspace at {DOC_ROOT}")


def artifact_status(state: dict, key: str) -> str:
    recorded = state.get("artifacts", {}).get(key, {}).get("status")
    if recorded:
        return recorded
    return "draft" if ARTIFACTS[key].exists() else "missing"


def mark_draft(args: argparse.Namespace) -> None:
    if args.artifact not in ARTIFACTS:
        fail(f"Unknown artifact: {args.artifact}")
    if not ARTIFACTS[args.artifact].exists():
        fail(f"Cannot mark missing artifact as draft: {ARTIFACTS[args.artifact]}")
    state = load_state()
    state["artifacts"][args.artifact] = {"path": str(ARTIFACTS[args.artifact]), "status": "draft"}
    save_state(state)
    print(f"Marked draft: {args.artifact}")


def approve(args: argparse.Namespace) -> None:
    if args.gate not in GATES:
        fail(f"Unknown gate: {args.gate}")

    state = load_state()
    missing = [key for key in GATES[args.gate] if not ARTIFACTS[key].exists()]
    if missing:
        fail("Cannot approve missing artifact(s): " + ", ".join(missing))

    for key in GATES[args.gate]:
        state["artifacts"][key] = {"path": str(ARTIFACTS[key]), "status": "approved"}

    state["approvals"].append(
        {"gate": args.gate, "approvedBy": args.approved_by, "approvedAt": now_iso()}
    )
    state["currentGate"] = NEXT_GATE[args.gate]
    save_state(state)
    print(f"Approved {args.gate}; current gate is {state['currentGate']}")


def require_approved(state: dict, keys: list[str], step: str) -> None:
    missing = [key for key in keys if artifact_status(state, key) != "approved"]
    if missing:
        fail(f"{step} is blocked. Approval required for: {', '.join(missing)}")


def can_run(args: argparse.Namespace) -> None:
    state = load_state()
    step = args.step
    if step == "step-one":
        if not ARTIFACTS["project-brief"].exists():
            fail("step-one is blocked. Missing docs/arquitecture/project-brief.md")
    elif step == "step-two":
        require_approved(state, ["phase-1-drivers"], step)
    elif step == "step-three":
        require_approved(state, ["phase-2-iteration-plan", "phase-2-decisions"], step)
    elif step == "step-four":
        require_approved(state, ["phase-3-document"], step)
    elif step == "slice":
        if not ARTIFACTS["phase-4-implementation-plan"].exists():
            fail("slice is blocked. Missing implementation-plan.md")
    else:
        fail(f"Unknown step: {step}")
    print(f"OK: {step} is unblocked")


def next_action(state: dict) -> str:
    if not ARTIFACTS["project-brief"].exists():
        return "@sam init"
    gate = state.get("currentGate", "brief")
    if gate == "brief":
        return "Review docs/arquitecture/project-brief.md, then run @sam step-one."
    if gate == "phase-1-drivers":
        return "Approve phase-1-drivers or revise @sam step-one."
    if gate == "phase-2-design":
        return "Run @sam step-two after phase-1-drivers is approved."
    if gate == "phase-3-document":
        return "Run @sam step-three after phase-2-design is approved."
    if gate == "phase-4-implementation":
        return "Run @sam step-four after phase-3-document is approved."
    return "SAM workflow complete."


def status(_args: argparse.Namespace) -> None:
    state = load_state()
    print(f"Root: {DOC_ROOT}")
    print(f"Current gate: {state.get('currentGate', 'brief')}")
    print("Artifacts:")
    for key, path in ARTIFACTS.items():
        print(f"- {key}: {artifact_status(state, key)} ({path})")
    print(f"Next: {next_action(state)}")


def next_cmd(_args: argparse.Namespace) -> None:
    print(next_action(load_state()))


def self_test(_args: argparse.Namespace) -> None:
    cwd = Path.cwd()
    with tempfile.TemporaryDirectory() as tmp:
        os.chdir(tmp)
        try:
            try:
                can_run(argparse.Namespace(step="step-one"))
            except SystemExit as exc:
                assert exc.code == 2
            else:
                raise AssertionError("step-one should fail before init")

            init(argparse.Namespace(name="Demo"))
            assert ARTIFACTS["project-brief"].exists()
            can_run(argparse.Namespace(step="step-one"))

            ARTIFACTS["phase-1-drivers"].write_text("# Drivers\n", encoding="utf-8")
            mark_draft(argparse.Namespace(artifact="phase-1-drivers"))
            approve(argparse.Namespace(gate="phase-1-drivers", approved_by="Architect"))
            can_run(argparse.Namespace(step="step-two"))

            state = load_state()
            assert state["currentGate"] == "phase-2-design"
            assert artifact_status(state, "phase-1-drivers") == "approved"
        finally:
            os.chdir(cwd)
    print("sam_state self-test passed")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="SAM state helper")
    sub = parser.add_subparsers(dest="command", required=True)

    init_p = sub.add_parser("init")
    init_p.add_argument("--name", default="Project")
    init_p.set_defaults(func=init)

    sub.add_parser("status").set_defaults(func=status)
    sub.add_parser("next").set_defaults(func=next_cmd)

    mark_p = sub.add_parser("mark-draft")
    mark_p.add_argument("artifact")
    mark_p.set_defaults(func=mark_draft)

    approve_p = sub.add_parser("approve")
    approve_p.add_argument("gate")
    approve_p.add_argument("--approved-by", default="Architect")
    approve_p.set_defaults(func=approve)

    can_p = sub.add_parser("can-run")
    can_p.add_argument("step")
    can_p.set_defaults(func=can_run)

    sub.add_parser("self-test").set_defaults(func=self_test)
    return parser


def main() -> None:
    args = build_parser().parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
