#!/usr/bin/env python3
"""Validate SAM examples against the v2 artifact and traceability contract."""

from __future__ import annotations

import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXAMPLES = ROOT / "examples"
OUTPUTS = {
    "drivers": Path("01-architectural-requirements/architecture-drivers.md"),
    "iterations": Path("02-architectural-design/iteration-plan.md"),
    "decisions": Path("02-architectural-design/design-decisions.md"),
    "document": Path("03-architectural-documentation/architecture-document.md"),
    "implementation": Path("04-architectural-implementation/implementation-plan.md"),
}
ALLOWED_STATUSES = {"Draft", "In Review", "Approved", "Superseded"}


def read(path: Path, errors: list[str]) -> str:
    if not path.exists():
        errors.append(f"missing {path.relative_to(ROOT)}")
        return ""
    return path.read_text(encoding="utf-8")


def validate_example(example: Path) -> list[str]:
    errors: list[str] = []
    texts = {name: read(example / relative, errors) for name, relative in OUTPUTS.items()}

    for name, text in texts.items():
        if not text:
            continue
        status = re.search(r"(?m)^Status: (.+)$", text)
        if not status or status.group(1).strip() not in ALLOWED_STATUSES:
            errors.append(f"{example.name}/{name}: invalid or missing Status")
        for field in ["Generated by", "Approved by", "Approved date", "Source artifacts"]:
            if not re.search(rf"(?m)^{re.escape(field)}:", text):
                errors.append(f"{example.name}/{name}: missing {field}")

    corpus = "\n".join(texts.values())
    for prefix in ["REQ", "QA", "CON", "DRV", "ADR", "STORY", "SLICE", "CHECK"]:
        if not re.search(rf"\b{prefix}-\d{{3}}\b", corpus):
            errors.append(f"{example.name}: missing stable {prefix} identifier")

    if re.search(r"Satisfied for design|Partially satisfied", corpus, re.IGNORECASE):
        errors.append(f"{example.name}: ambiguous design-validation status")
    if re.search(r"(?m)^\| DRV-\d{3} \| Verified \|", texts["decisions"]):
        errors.append(f"{example.name}: design phase must not claim Verified")

    primary_drivers = set(
        re.findall(r"(?m)^\| (DRV-\d{3}) \| [^|]+ \| Primary \|$", texts["drivers"])
    )
    if not primary_drivers:
        errors.append(f"{example.name}: no primary DRV crosswalk")
    for driver in sorted(primary_drivers):
        for artifact in ["decisions", "document", "implementation"]:
            if driver not in texts[artifact]:
                errors.append(f"{example.name}: {driver} missing from {artifact}")

        decision_row = re.search(
            rf"(?m)^\| {driver} \| (?:Addressed|Pending|Accepted Risk) \| (ADR-\d{{3}}) \| (CHECK-\d{{3}})",
            texts["decisions"],
        )
        if not decision_row:
            errors.append(f"{example.name}: {driver} lacks design coverage and pending check")
        document_row = re.search(
            rf"(?m)^\| REQ-\d{{3}} \| QA-\d{{3}} \| {driver} \| ADR-\d{{3}} \| STORY-\d{{3}} \| CHECK-\d{{3}} \| (?:Pending|Verified|Failed|Accepted Risk) \|$",
            texts["document"],
        )
        if not document_row:
            errors.append(f"{example.name}: {driver} lacks complete document traceability")
        implementation_row = re.search(
            rf"(?m)^\| {driver} \| SLICE-\d{{3}} \| CHECK-\d{{3}} ",
            texts["implementation"],
        )
        if not implementation_row:
            errors.append(f"{example.name}: {driver} lacks slice/check traceability")

    for name in ["drivers", "iterations", "decisions", "document", "implementation"]:
        if "Exit Checklist" not in texts[name] or re.search(r"(?m)^- \[ \]", texts[name]):
            errors.append(f"{example.name}/{name}: exit checklist missing or incomplete")
    return errors


def main() -> int:
    errors: list[str] = []
    examples = sorted(path for path in EXAMPLES.iterdir() if path.is_dir())
    for example in examples:
        errors.extend(validate_example(example))

    add_text = (ROOT / "method/02-architectural-design/ADD.md").read_text(encoding="utf-8")
    forbidden_add_dependencies = [
        "review the approved drivers, the architecture document",
        "modify the diagrams in the architecture document",
        "update the traceability matrix in the architecture document",
    ]
    if any(phrase in add_text.lower() for phrase in forbidden_add_dependencies):
        errors.append("ADD still consumes the phase 3 architecture document")

    if errors:
        print("SAM example validation failed:")
        for error in errors:
            print(f"- {error}")
        return 1
    print(f"SAM example validation passed for {len(examples)} examples")
    return 0


if __name__ == "__main__":
    sys.exit(main())
